### ISSUE TITLE
How to extract the edge correctly?

### ISSUE THREAD

**Issue by thachdo** [denabazazian/Edge_Extraction#3]
I am trying to implement your source to extract edges from an STL file.
First, I convert STL to PLYfile. The PLY file is as follows:
![image](https://user-images.githubusercontent.com/5842637/109771588-90d33500-7c2f-11eb-935e-7326fd567f0a.png)

Then, I use the python [code](https://github.com/denabazazian/Edge_Extraction/blob/master/Difference_Eigenvalues.py) to extract the edge. However, the result looks incorrect/unexpected:
![image](https://user-images.githubusercontent.com/5842637/109771385-523d7a80-7c2f-11eb-865c-86187ccb7b46.png)

Here, I set the parameters as `k_n = 150` and `thresh = 0.003`

Could you please give me some instructions to get better results, which are the edges of the objects? (how can I select proper `k_n` and `thresh` parameters?)

**Comment by denabazazian** [comment]
`k_n` stands for the number of neighbors, so you should define this parameter based on the density of your point cloud. If your point cloud is very dense, then your value should be larger, otherwise if the points in your point cloud are sparse, then you should consider a lower value for `k_n`. 
The value of `thresh` is based on the eigenvalues. In order to define the best threshold on your data, you can comment the line [46](https://github.com/denabazazian/Edge_Extraction/blob/master/Difference_Eigenvalues.py#L46) of the code. Then, check the visualization of line [57](https://github.com/denabazazian/Edge_Extraction/blob/master/Difference_Eigenvalues.py#L57). There, you can define the proper threshold based on the 'colorbar' and the visualization that you get on the edges. 

It would be better to keep the `thresh` as a fix number and play with different `k_n` values first to find the proper number of neighbors, since this value can be different depends on the density of your point cloud. But, `thresh` is usually a same value on most of the cases. 
 
I hope this clarifies your query, let me know if you have any further problem, and thanks for your interest in this code.

**Comment by thachdo** [comment]
As your suggestion, I fixed the `thresh =0.03` param. I tried with different `k_n` from 1 to the maximum value of `k_neighbors`. However, it was not much difference between the trial values of `k_n`. I couldn't extract any information from the inner edges.
I also attached the .ply here. Can you try it?
[BoxFirmaSchublade.zip](https://github.com/denabazazian/Edge_Extraction/files/6084266/BoxFirmaSchublade.zip)
