### ISSUE TITLE
Curvature( Sigma[i]) is awlays small values.

### ISSUE THREAD

**Issue by vahidaidrivers** [denabazazian/Edge_Extraction#5]
I have tried many values of KNumbersNeighbor (2,20,200,2000). Sigma is a small value which means all points belong to flat planes. But there are 3 90-degree edges. Could you please advise how your method works for finding the edges?

**Comment by denabazazian** [comment]
There are two following parameters in this code, you can find the correct value of each one of these two parameters depending on the density of your point cloud and the degree of the edges that you are interested in detecting. 

1. [KNumbersNeighbor](https://github.com/denabazazian/Edge_Extraction/blob/master/Difference_Eigenvalues.cpp#L72):
 The first parameter is the number of neighbourhoods which should be defined in order to compute the Eigenvalue and Eigenvector. This parameter highly depends on the density of the point cloud. If in your point cloud the distribution of the points is unified then after a couple of experiments you can come up with the right number. You should consider a higher number in case of a high density of point clouds and a lower number for sparse point clouds. This number should be defined by this conception that if your sample point is located on an edge part then part of its neighbours should be located on the flat parts around the sample point. You can visualize your point cloud and see how is the density around the edges and in the line of the edge part.

2. [Sigma](https://github.com/denabazazian/Edge_Extraction/blob/master/Difference_Eigenvalues.cpp#L291):
 The second parameter is for the Sigma which is the difference of Eigenvalues. From my point of view in your case, you can define a low threshold since your objective is to detect the stairs then you have just flat and the edges which the dihedral is 90 degrees. Sigma for the exact flat surfaces is always zero since it is the length of the normal vector and if the only edge area that exists in your point cloud has the dihedral of 90 degrees then if you consider the StepMultiplier as one or two, it should work although it is important if you assign an adequate number for the neighbourhoods (KNumbersNeighbor).
